# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/torimerge/cli.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'torimerge.excel_loader',
        'torimerge.group_merge', 
        'torimerge.template_engine',
        'torimerge.eml_builder',
        'torimerge.types',
        'pandas',
        'pandas._libs.tslibs.base',
        'pandas._libs.tslibs.ccalendar',
        'pandas._libs.tslibs.dtypes',
        'pandas._libs.tslibs.field_array',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.offsets',
        'pandas._libs.tslibs.parsing',
        'pandas._libs.tslibs.period',
        'pandas._libs.tslibs.strptime',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.timestamps',
        'pandas._libs.tslibs.timezones',
        'pandas._libs.tslibs.tzconversion',
        'pandas._libs.tslibs.vectorized',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.cell',
        'jinja2',
        'jinja2.ext',
        'email',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'email.header',
        'argparse',
        'pathlib',
        'sys',
        'os'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='torimerge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
